openapi: 3.0.1
info:
  description: ""
  title: Notes
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "If you had an offline conversation with a customer, you\
    \ could add a note to their contact record with the important takeaways from your\
    \ conversation."
  x-hubspot-related-documentation:
  - name: Notes Guide
    url: https://developers.hubspot.com/docs/guides/api/crm/engagements/notes
  x-hubspot-introduction: Use the notes engagements API to include contextual information
    or associate an attachment with a CRM record. Other users in your HubSpot account
    will then be able to review the note and any attachments.
servers:
- url: https://api.hubapi.com
tags:
- name: Batch
- name: Basic
- name: Search
paths:
  /crm/v3/objects/notes/batch/read:
    post:
      operationId: post-/crm/v3/objects/notes/batch/read_read
      parameters:
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchReadInputSimplePublicObjectId"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicObject"
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicObjectWithErrors"
          description: multiple statuses
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: "Read a batch of notes by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/notes/{noteId}:
    delete:
      description: "Move an Object identified by `{noteId}` to the recycling bin."
      operationId: "delete-/crm/v3/objects/notes/{noteId}_archive"
      parameters:
      - explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          content: {}
          description: No content
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Archive
      tags:
      - Basic
    get:
      description: "Read an Object identified by `{noteId}`. `{noteId}` refers to\
        \ the internal object ID by default, or optionally any unique property value\
        \ as specified by the `idProperty` query param.  Control what is returned\
        \ via the `properties` query param."
      operationId: "get-/crm/v3/objects/notes/{noteId}_getById"
      parameters:
      - explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      - description: "A comma separated list of the properties to be returned in the\
          \ response. If any of the specified properties are not present on the requested\
          \ object(s), they will be ignored."
        explode: true
        in: query
        name: properties
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of the properties to be returned along\
          \ with their history of previous values. If any of the specified properties\
          \ are not present on the requested object(s), they will be ignored."
        explode: true
        in: query
        name: propertiesWithHistory
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of object types to retrieve associated\
          \ IDs for. If any of the specified associations do not exist, they will\
          \ be ignored."
        explode: true
        in: query
        name: associations
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: The name of a property whose values are unique for this object
          type
        explode: true
        in: query
        name: idProperty
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimplePublicObjectWithAssociations"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: Read
      tags:
      - Basic
    patch:
      description: "Perform a partial update of an Object identified by `{noteId}`.\
        \ `{noteId}` refers to the internal object ID by default, or optionally any\
        \ unique property value as specified by the `idProperty` query param. Provided\
        \ property values will be overwritten. Read-only and non-existent properties\
        \ will be ignored. Properties values can be cleared by passing an empty string."
      operationId: "patch-/crm/v3/objects/notes/{noteId}_update"
      parameters:
      - explode: false
        in: path
        name: noteId
        required: true
        schema:
          type: string
        style: simple
      - description: The name of a property whose values are unique for this object
          type
        explode: true
        in: query
        name: idProperty
        required: false
        schema:
          type: string
        style: form
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimplePublicObjectInput"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimplePublicObject"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Update
      tags:
      - Basic
  /crm/v3/objects/notes/batch/archive:
    post:
      operationId: post-/crm/v3/objects/notes/batch/archive_archive
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchInputSimplePublicObjectId"
        required: true
      responses:
        "204":
          content: {}
          description: No content
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Archive a batch of notes by ID
      tags:
      - Batch
  /crm/v3/objects/notes/batch/create:
    post:
      operationId: post-/crm/v3/objects/notes/batch/create_create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchInputSimplePublicObjectInputForCreate"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicObject"
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicObjectWithErrors"
          description: multiple statuses
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create a batch of notes
      tags:
      - Batch
  /crm/v3/objects/notes/batch/update:
    post:
      operationId: post-/crm/v3/objects/notes/batch/update_update
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchInputSimplePublicObjectBatchInput"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicObject"
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicObjectWithErrors"
          description: multiple statuses
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: "Update a batch of notes by internal ID, or unique property values"
      tags:
      - Batch
  /crm/v3/objects/notes:
    get:
      description: Read a page of notes. Control what is returned via the `properties`
        query param.
      operationId: get-/crm/v3/objects/notes_getPage
      parameters:
      - description: The maximum number of results to display per page.
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          format: int32
          type: integer
        style: form
      - description: The paging cursor token of the last successfully read resource
          will be returned as the `paging.next.after` JSON property of a paged response
          containing more results.
        explode: true
        in: query
        name: after
        required: false
        schema:
          type: string
        style: form
      - description: "A comma separated list of the properties to be returned in the\
          \ response. If any of the specified properties are not present on the requested\
          \ object(s), they will be ignored."
        explode: true
        in: query
        name: properties
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of the properties to be returned along\
          \ with their history of previous values. If any of the specified properties\
          \ are not present on the requested object(s), they will be ignored. Usage\
          \ of this parameter will reduce the maximum number of objects that can be\
          \ read by a single request."
        explode: true
        in: query
        name: propertiesWithHistory
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "A comma separated list of object types to retrieve associated\
          \ IDs for. If any of the specified associations do not exist, they will\
          \ be ignored."
        explode: true
        in: query
        name: associations
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Whether to return only results that have been archived.
        explode: true
        in: query
        name: archived
        required: false
        schema:
          default: false
          type: boolean
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectionResponseSimplePublicObjectWithAssociationsForwardPaging"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      summary: List
      tags:
      - Basic
    post:
      description: "Create a note with the given properties and return a copy of the\
        \ object, including the ID. Documentation and examples for creating standard\
        \ notes is provided."
      operationId: post-/crm/v3/objects/notes_create
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SimplePublicObjectInputForCreate"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimplePublicObject"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create
      tags:
      - Basic
  /crm/v3/objects/notes/batch/upsert:
    post:
      description: Create or update records identified by a unique property value
        as specified by the `idProperty` query param. `idProperty` query param refers
        to a property whose values are unique for the object.
      operationId: post-/crm/v3/objects/notes/batch/upsert_upsert
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BatchInputSimplePublicObjectBatchInputUpsert"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicUpsertObject"
          description: successful operation
        "207":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BatchResponseSimplePublicUpsertObjectWithErrors"
          description: multiple statuses
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.write
      - private_apps:
        - crm.objects.contacts.write
      summary: Create or update a batch of notes by unique property values
      tags:
      - Batch
  /crm/v3/objects/notes/search:
    post:
      operationId: post-/crm/v3/objects/notes/search_doSearch
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PublicObjectSearchRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CollectionResponseWithTotalSimplePublicObjectForwardPaging"
          description: successful operation
        default:
          $ref: "#/components/responses/Error"
      security:
      - oauth2:
        - crm.objects.contacts.read
      - private_apps:
        - crm.objects.contacts.read
      tags:
      - Search
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  responses:
    Error:
      content:
        '*/*':
          schema:
            $ref: "#/components/schemas/Error"
      description: An error occurred.
  schemas:
    StandardError:
      example:
        subCategory: "{}"
        context:
          key:
          - context
          - context
        links:
          key: links
        id: id
        category: category
        message: message
        errors:
        - subCategory: subCategory
          code: code
          in: in
          context:
            missingScopes:
            - scope1
            - scope2
          message: message
        - subCategory: subCategory
          code: code
          in: in
          context:
            missingScopes:
            - scope1
            - scope2
          message: message
        status: status
      properties:
        subCategory:
          properties: {}
          type: object
        context:
          additionalProperties:
            items:
              type: string
            type: array
          type: object
        links:
          additionalProperties:
            type: string
          type: object
        id:
          type: string
        category:
          type: string
        message:
          type: string
        errors:
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type: array
        status:
          type: string
      required:
      - category
      - context
      - errors
      - links
      - message
      - status
      type: object
    CollectionResponseAssociatedId:
      properties:
        paging:
          $ref: "#/components/schemas/Paging"
        results:
          items:
            $ref: "#/components/schemas/AssociatedId"
          type: array
      required:
      - results
      type: object
    PublicAssociationsForObject:
      properties:
        types:
          items:
            $ref: "#/components/schemas/AssociationSpec"
          type: array
        to:
          $ref: "#/components/schemas/PublicObjectId"
      required:
      - to
      - types
      type: object
    BatchResponseSimplePublicObject:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - id: "512"
          properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        - id: "512"
          properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: "#/components/schemas/SimplePublicObject"
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    FilterGroup:
      example:
        filters:
        - highValue: highValue
          propertyName: propertyName
          values:
          - values
          - values
          value: value
          operator: EQ
        - highValue: highValue
          propertyName: propertyName
          values:
          - values
          - values
          value: value
          operator: EQ
      properties:
        filters:
          items:
            $ref: "#/components/schemas/Filter"
          type: array
      required:
      - filters
      type: object
    ErrorDetail:
      example:
        subCategory: subCategory
        code: code
        in: in
        context:
          missingScopes:
          - scope1
          - scope2
        message: message
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        code:
          description: The status code associated with the error detail
          type: string
        in:
          description: The name of the field or parameter in which the error was found.
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          type: string
      required:
      - message
      type: object
    ForwardPaging:
      example:
        next:
          after: NTI1Cg%3D%3D
          link: ?after=NTI1Cg%3D%3D
      properties:
        next:
          $ref: "#/components/schemas/NextPage"
      type: object
    SimplePublicObjectId:
      example:
        id: id
      properties:
        id:
          type: string
      required:
      - id
      type: object
    BatchResponseSimplePublicUpsertObjectWithErrors:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        numErrors: 6
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          archived: true
          archivedAt: 2000-01-23T04:56:07.000+00:00
          new: true
          propertiesWithHistory:
            key:
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
          id: id
          properties:
            key: properties
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          archived: true
          archivedAt: 2000-01-23T04:56:07.000+00:00
          new: true
          propertiesWithHistory:
            key:
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
          id: id
          properties:
            key: properties
          updatedAt: 2000-01-23T04:56:07.000+00:00
        errors:
        - subCategory: "{}"
          context:
            key:
            - context
            - context
          links:
            key: links
          id: id
          category: category
          message: message
          errors:
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          status: status
        - subCategory: "{}"
          context:
            key:
            - context
            - context
          links:
            key: links
          id: id
          category: category
          message: message
          errors:
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          status: status
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        numErrors:
          format: int32
          type: integer
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: "#/components/schemas/SimplePublicUpsertObject"
          type: array
        errors:
          items:
            $ref: "#/components/schemas/StandardError"
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    BatchReadInputSimplePublicObjectId:
      example:
        propertiesWithHistory:
        - propertiesWithHistory
        - propertiesWithHistory
        idProperty: idProperty
        inputs:
        - id: id
        - id: id
        properties:
        - properties
        - properties
      properties:
        propertiesWithHistory:
          items:
            type: string
          type: array
        idProperty:
          type: string
        inputs:
          items:
            $ref: "#/components/schemas/SimplePublicObjectId"
          type: array
        properties:
          items:
            type: string
          type: array
      required:
      - inputs
      - properties
      - propertiesWithHistory
      type: object
    BatchResponseSimplePublicUpsertObject:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - createdAt: 2000-01-23T04:56:07.000+00:00
          archived: true
          archivedAt: 2000-01-23T04:56:07.000+00:00
          new: true
          propertiesWithHistory:
            key:
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
          id: id
          properties:
            key: properties
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - createdAt: 2000-01-23T04:56:07.000+00:00
          archived: true
          archivedAt: 2000-01-23T04:56:07.000+00:00
          new: true
          propertiesWithHistory:
            key:
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
            - sourceId: sourceId
              sourceType: sourceType
              sourceLabel: sourceLabel
              updatedByUserId: 0
              value: value
              timestamp: 2000-01-23T04:56:07.000+00:00
          id: id
          properties:
            key: properties
          updatedAt: 2000-01-23T04:56:07.000+00:00
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: "#/components/schemas/SimplePublicUpsertObject"
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    BatchInputSimplePublicObjectId:
      example:
        inputs:
        - id: id
        - id: id
      properties:
        inputs:
          items:
            $ref: "#/components/schemas/SimplePublicObjectId"
          type: array
      required:
      - inputs
      type: object
    ValueWithTimestamp:
      example:
        sourceId: sourceId
        sourceType: sourceType
        sourceLabel: sourceLabel
        updatedByUserId: 0
        value: value
        timestamp: 2000-01-23T04:56:07.000+00:00
      properties:
        sourceId:
          type: string
        sourceType:
          type: string
        sourceLabel:
          type: string
        updatedByUserId:
          format: int32
          type: integer
        value:
          type: string
        timestamp:
          format: date-time
          type: string
      required:
      - sourceType
      - timestamp
      - value
      type: object
    BatchInputSimplePublicObjectBatchInputUpsert:
      example:
        inputs:
        - idProperty: idProperty
          objectWriteTraceId: objectWriteTraceId
          id: id
          properties:
            key: properties
        - idProperty: idProperty
          objectWriteTraceId: objectWriteTraceId
          id: id
          properties:
            key: properties
      properties:
        inputs:
          items:
            $ref: "#/components/schemas/SimplePublicObjectBatchInputUpsert"
          type: array
      required:
      - inputs
      type: object
    CollectionResponseWithTotalSimplePublicObjectForwardPaging:
      example:
        total: 0
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
        results:
        - id: "512"
          properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        - id: "512"
          properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
      properties:
        total:
          format: int32
          type: integer
        paging:
          $ref: "#/components/schemas/ForwardPaging"
        results:
          items:
            $ref: "#/components/schemas/SimplePublicObject"
          type: array
      required:
      - results
      - total
      type: object
    SimplePublicObject:
      example:
        id: "512"
        properties:
          createdate: 2019-10-30T03:30:17.883Z
          hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
          hs_note_body: Spoke with decision maker john
          hs_timestamp: 2019-10-30T03:30:17.883Z
          hubspot_owner_id: "11349275740"
        createdAt: 2019-10-30T03:30:17.883Z
        updatedAt: 2019-12-07T16:50:06.678Z
        archived: false
      properties:
        createdAt:
          format: date-time
          type: string
        archived:
          example: false
          type: boolean
        archivedAt:
          format: date-time
          type: string
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: "#/components/schemas/ValueWithTimestamp"
            type: array
          type: object
        id:
          example: "512"
          type: string
        properties:
          additionalProperties:
            nullable: true
            type: string
          example:
            property_date: "1572480000000"
            property_radio: option_1
            property_number: "17"
            property_string: value
            property_checkbox: "false"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - properties
      - updatedAt
      type: object
    PublicObjectId:
      properties:
        id:
          type: string
      required:
      - id
      type: object
    Paging:
      properties:
        next:
          $ref: "#/components/schemas/NextPage"
        prev:
          $ref: "#/components/schemas/PreviousPage"
      type: object
    PublicObjectSearchRequest:
      example:
        query: query
        limit: 0
        after: after
        sorts:
        - sorts
        - sorts
        properties:
        - properties
        - properties
        filterGroups:
        - filters:
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
        - filters:
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
          - highValue: highValue
            propertyName: propertyName
            values:
            - values
            - values
            value: value
            operator: EQ
      properties:
        query:
          type: string
        limit:
          format: int32
          type: integer
        after:
          type: string
        sorts:
          items:
            type: string
          type: array
        properties:
          items:
            type: string
          type: array
        filterGroups:
          items:
            $ref: "#/components/schemas/FilterGroup"
          type: array
      type: object
    Error:
      example:
        message: Invalid input (details will vary based on the error)
        correlationId: aeb5f871-7f07-4993-9211-075dc63e7cbf
        category: VALIDATION_ERROR
        links:
          knowledge-base: https://www.hubspot.com/products/service/knowledge-base
      properties:
        subCategory:
          description: A specific category that contains more specific detail about
            the error
          type: string
        context:
          additionalProperties:
            items:
              type: string
            type: array
          description: Context about the error condition
          example:
            missingScopes:
            - scope1
            - scope2
            invalidPropertyName:
            - propertyValue
          type: object
        correlationId:
          description: A unique identifier for the request. Include this value with
            any error reports or support tickets
          example: aeb5f871-7f07-4993-9211-075dc63e7cbf
          format: uuid
          type: string
        links:
          additionalProperties:
            type: string
          description: A map of link names to associated URIs containing documentation
            about the error or recommended remediation steps
          example:
            knowledge-base: https://www.hubspot.com/products/service/knowledge-base
          type: object
        message:
          description: A human readable message describing the error along with remediation
            steps where appropriate
          example: Invalid input (details will vary based on the error)
          type: string
        category:
          description: The error category
          example: VALIDATION_ERROR
          type: string
        errors:
          description: further information about the error
          items:
            $ref: "#/components/schemas/ErrorDetail"
          type: array
      required:
      - category
      - correlationId
      - message
      type: object
    SimplePublicObjectBatchInputUpsert:
      example:
        idProperty: idProperty
        objectWriteTraceId: objectWriteTraceId
        id: id
        properties:
          key: properties
      properties:
        idProperty:
          type: string
        objectWriteTraceId:
          type: string
        id:
          type: string
        properties:
          additionalProperties:
            type: string
          type: object
      required:
      - id
      - properties
      type: object
    BatchResponseSimplePublicObjectWithErrors:
      example:
        completedAt: 2000-01-23T04:56:07.000+00:00
        numErrors: 0
        requestedAt: 2000-01-23T04:56:07.000+00:00
        startedAt: 2000-01-23T04:56:07.000+00:00
        links:
          key: links
        results:
        - id: "512"
          properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        - id: "512"
          properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          createdAt: 2019-10-30T03:30:17.883Z
          updatedAt: 2019-12-07T16:50:06.678Z
          archived: false
        errors:
        - subCategory: "{}"
          context:
            key:
            - context
            - context
          links:
            key: links
          id: id
          category: category
          message: message
          errors:
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          status: status
        - subCategory: "{}"
          context:
            key:
            - context
            - context
          links:
            key: links
          id: id
          category: category
          message: message
          errors:
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          - subCategory: subCategory
            code: code
            in: in
            context:
              missingScopes:
              - scope1
              - scope2
            message: message
          status: status
        status: PENDING
      properties:
        completedAt:
          format: date-time
          type: string
        numErrors:
          format: int32
          type: integer
        requestedAt:
          format: date-time
          type: string
        startedAt:
          format: date-time
          type: string
        links:
          additionalProperties:
            type: string
          type: object
        results:
          items:
            $ref: "#/components/schemas/SimplePublicObject"
          type: array
        errors:
          items:
            $ref: "#/components/schemas/StandardError"
          type: array
        status:
          enum:
          - PENDING
          - PROCESSING
          - CANCELED
          - COMPLETE
          type: string
      required:
      - completedAt
      - results
      - startedAt
      - status
      type: object
    SimplePublicObjectInput:
      example:
        properties:
          hs_note_body: Spoke with decision maker john
          hs_timestamp: 2019-10-30T03:30:17.883Z
          hubspot_owner_id: "11349275740"
        associations:
        - to:
            id: "101"
          types:
          - associationCategory: HUBSPOT_DEFINED
            associationTypeId: 2
      properties:
        objectWriteTraceId:
          type: string
        properties:
          additionalProperties:
            type: string
          example:
            property_date: "1572480000000"
            property_radio: option_1
            property_number: "17"
            property_string: value
            property_checkbox: "false"
            property_dropdown: choice_b
            property_multiple_checkboxes: chocolate;strawberry
          type: object
      required:
      - properties
      type: object
    CollectionResponseSimplePublicObjectWithAssociationsForwardPaging:
      example:
        paging:
          next:
            after: NTI1Cg%3D%3D
            link: ?after=NTI1Cg%3D%3D
        results:
        - properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
        - properties:
            createdate: 2019-10-30T03:30:17.883Z
            hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
      properties:
        paging:
          $ref: "#/components/schemas/ForwardPaging"
        results:
          items:
            $ref: "#/components/schemas/SimplePublicObjectWithAssociations"
          type: array
      required:
      - results
      type: object
    AssociationSpec:
      properties:
        associationCategory:
          enum:
          - HUBSPOT_DEFINED
          - USER_DEFINED
          - INTEGRATOR_DEFINED
          type: string
        associationTypeId:
          format: int32
          type: integer
      required:
      - associationCategory
      - associationTypeId
      type: object
    SimplePublicObjectWithAssociations:
      example:
        properties:
          createdate: 2019-10-30T03:30:17.883Z
          hs_lastmodifieddate: 2019-12-07T16:50:06.678Z
          hs_note_body: Spoke with decision maker john
          hs_timestamp: 2019-10-30T03:30:17.883Z
          hubspot_owner_id: "11349275740"
      properties:
        associations:
          additionalProperties:
            $ref: "#/components/schemas/CollectionResponseAssociatedId"
          type: object
        createdAt:
          format: date-time
          type: string
        archived:
          type: boolean
        archivedAt:
          format: date-time
          type: string
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: "#/components/schemas/ValueWithTimestamp"
            type: array
          type: object
        id:
          type: string
        properties:
          additionalProperties:
            nullable: true
            type: string
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - properties
      - updatedAt
      type: object
    Filter:
      example:
        highValue: highValue
        propertyName: propertyName
        values:
        - values
        - values
        value: value
        operator: EQ
      properties:
        highValue:
          type: string
        propertyName:
          type: string
        values:
          items:
            type: string
          type: array
        value:
          type: string
        operator:
          description: "null"
          enum:
          - EQ
          - NEQ
          - LT
          - LTE
          - GT
          - GTE
          - BETWEEN
          - IN
          - NOT_IN
          - HAS_PROPERTY
          - NOT_HAS_PROPERTY
          - CONTAINS_TOKEN
          - NOT_CONTAINS_TOKEN
          type: string
      required:
      - operator
      - propertyName
      type: object
    BatchInputSimplePublicObjectBatchInput:
      example:
        inputs:
        - id: "1"
          properties:
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
        - id: "1"
          properties:
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
      properties:
        inputs:
          items:
            $ref: "#/components/schemas/SimplePublicObjectBatchInput"
          type: array
      required:
      - inputs
      type: object
    BatchInputSimplePublicObjectInputForCreate:
      example:
        inputs:
        - properties:
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          associations:
          - to:
              id: "101"
            types:
            - associationCategory: HUBSPOT_DEFINED
              associationTypeId: 2
        - properties:
            hs_note_body: Spoke with decision maker john
            hs_timestamp: 2019-10-30T03:30:17.883Z
            hubspot_owner_id: "11349275740"
          associations:
          - to:
              id: "101"
            types:
            - associationCategory: HUBSPOT_DEFINED
              associationTypeId: 2
      properties:
        inputs:
          items:
            $ref: "#/components/schemas/SimplePublicObjectInputForCreate"
          type: array
      required:
      - inputs
      type: object
    PreviousPage:
      properties:
        before:
          type: string
        link:
          type: string
      required:
      - before
      type: object
    SimplePublicUpsertObject:
      example:
        createdAt: 2000-01-23T04:56:07.000+00:00
        archived: true
        archivedAt: 2000-01-23T04:56:07.000+00:00
        new: true
        propertiesWithHistory:
          key:
          - sourceId: sourceId
            sourceType: sourceType
            sourceLabel: sourceLabel
            updatedByUserId: 0
            value: value
            timestamp: 2000-01-23T04:56:07.000+00:00
          - sourceId: sourceId
            sourceType: sourceType
            sourceLabel: sourceLabel
            updatedByUserId: 0
            value: value
            timestamp: 2000-01-23T04:56:07.000+00:00
        id: id
        properties:
          key: properties
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        createdAt:
          format: date-time
          type: string
        archived:
          type: boolean
        archivedAt:
          format: date-time
          type: string
        new:
          type: boolean
        propertiesWithHistory:
          additionalProperties:
            items:
              $ref: "#/components/schemas/ValueWithTimestamp"
            type: array
          type: object
        id:
          type: string
        properties:
          additionalProperties:
            type: string
          type: object
        updatedAt:
          format: date-time
          type: string
      required:
      - createdAt
      - id
      - new
      - properties
      - updatedAt
      type: object
    SimplePublicObjectBatchInput:
      example:
        id: "1"
        properties:
          hs_note_body: Spoke with decision maker john
          hs_timestamp: 2019-10-30T03:30:17.883Z
          hubspot_owner_id: "11349275740"
      properties:
        idProperty:
          example: my_unique_property_name
          type: string
        objectWriteTraceId:
          type: string
        id:
          type: string
        properties:
          additionalProperties:
            type: string
          type: object
      required:
      - id
      - properties
      type: object
    AssociatedId:
      properties:
        id:
          type: string
        type:
          type: string
      required:
      - id
      - type
      type: object
    NextPage:
      example:
        after: NTI1Cg%3D%3D
        link: ?after=NTI1Cg%3D%3D
      properties:
        link:
          example: ?after=NTI1Cg%3D%3D
          type: string
        after:
          example: NTI1Cg%3D%3D
          type: string
      required:
      - after
      type: object
    SimplePublicObjectInputForCreate:
      example:
        properties:
          hs_note_body: Spoke with decision maker john
          hs_timestamp: 2019-10-30T03:30:17.883Z
          hubspot_owner_id: "11349275740"
        associations:
        - to:
            id: "101"
          types:
          - associationCategory: HUBSPOT_DEFINED
            associationTypeId: 2
      properties:
        associations:
          items:
            $ref: "#/components/schemas/PublicAssociationsForObject"
          type: array
        objectWriteTraceId:
          type: string
        properties:
          additionalProperties:
            type: string
          type: object
      required:
      - associations
      - properties
      type: object
  securitySchemes:
    oauth2_legacy:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.custom.read: View custom object records
            tickets: Read and write tickets
            crm.objects.goals.read: Read goals
            media_bridge.read: Read media and media events
            crm.objects.custom.write: Change custom object records
            e-commerce: e-commerce
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.objects.services.read: Read services
            crm.objects.quotes.read: Quotes
            crm.objects.orders.write: Write orders
            crm.objects.carts.read: Read carts
            crm.objects.subscriptions.read: Read Commerce Subscriptions
            crm.objects.leads.write: Modify lead objects
            crm.objects.commercepayments.read: Read the COMMERCE_PAYMENT object.
            crm.objects.users.write: Write User CRM objects
            crm.objects.contacts.write: ' '
            crm.objects.companies.write: ' '
            crm.objects.listings.write: Write listings
            crm.objects.line_items.write: Line Items
            crm.objects.deals.write: ' '
            crm.objects.partner-clients.read: View Partner Client CRM objects
            crm.objects.invoices.read: Read invoices objects
            crm.objects.deals.read: ' '
            crm.objects.courses.read: Read courses
            crm.objects.line_items.read: Line Items
            crm.objects.services.write: Write services
            crm.objects.appointments.write: Write appointments
            crm.objects.leads.read: Read lead objects
            crm.objects.partner-clients.write: Modify Partner Client CRM objects
            crm.objects.appointments.read: Read appointments
            crm.objects.companies.read: ' '
            crm.objects.users.read: Read User CRM objects
            crm.objects.quotes.write: Quotes
            crm.objects.courses.write: Write courses
            crm.objects.carts.write: Write cart
            crm.objects.listings.read: Read listings
            crm.objects.contacts.read: ' '
            crm.objects.orders.read: Read Orders
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps_legacy:
      in: header
      name: private-app-legacy
      type: apiKey
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
x-hubspot-documentation-banner: NONE
